package dev.knalis.notification.entity;

public enum NotificationType {
    WELCOME,
    EMAIL_CHANGED,
    USERNAME_CHANGED,
    USER_BANNED,
    USER_UNBANNED,
    SCHEDULE_LESSON_CANCELLED,
    SCHEDULE_LESSON_CHANGED,
    SCHEDULE_EXTRA_LESSON,
    SCHEDULE_ROOM_CHANGED,
    SCHEDULE_FORMAT_CHANGED,
    SCHEDULE_TEACHER_CHANGED,
    ASSIGNMENT_CREATED,
    ASSIGNMENT_UPDATED,
    ASSIGNMENT_DEADLINE_REMINDER,
    GRADE_ASSIGNED,
    TEST_PUBLISHED,
    TEST_DEADLINE_REMINDER,
    LESSON_REMINDER,
    GENERIC
}
